-- ======================================================================
-- 申込管理システム DDL（07. テーブル定義 版 0.2）
-- SQL Server 2019 用。開発時の検証では H2（MSSQLServer 互換モード）でも流せる構文に限定している。
-- 共通項目：CREATED_AT / CREATED_BY / UPDATED_AT / UPDATED_BY / ROW_VERSION（楽観排他）
-- ======================================================================

-- 4.1 会社区分マスタ
CREATE TABLE M_COMPANY_DIV (
    COMPANY_DIV        CHAR(1)        NOT NULL,
    COMPANY_DIV_NAME   NVARCHAR(50)   NOT NULL,
    PRE_CHECK_FLG      CHAR(1)        NOT NULL,
    AMOUNT_RATIO_LIMIT DECIMAL(3,2)   NOT NULL,
    CREATED_AT         DATETIME2(3)   NOT NULL,
    CREATED_BY         NVARCHAR(20)   NOT NULL,
    UPDATED_AT         DATETIME2(3)   NOT NULL,
    UPDATED_BY         NVARCHAR(20)   NOT NULL,
    ROW_VERSION        INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_M_COMPANY_DIV PRIMARY KEY (COMPANY_DIV)
);

-- 4.2 社員マスタ
CREATE TABLE M_EMPLOYEE (
    EMPLOYEE_ID    BIGINT IDENTITY(1,1) NOT NULL,
    EMPLOYEE_NO    NVARCHAR(10)   NOT NULL,
    EMPLOYEE_NAME  NVARCHAR(50)   NOT NULL,
    PASSWORD_HASH  NVARCHAR(100)  NOT NULL,
    COMPANY_DIV    CHAR(1)        NOT NULL,
    DEPT_CD        NVARCHAR(10)   NOT NULL,
    ROLE_CD        CHAR(2)        NOT NULL,
    MAIL_ADDRESS   NVARCHAR(254)  NOT NULL,
    VALID_FLG      CHAR(1)        NOT NULL,
    CREATED_AT     DATETIME2(3)   NOT NULL,
    CREATED_BY     NVARCHAR(20)   NOT NULL,
    UPDATED_AT     DATETIME2(3)   NOT NULL,
    UPDATED_BY     NVARCHAR(20)   NOT NULL,
    ROW_VERSION    INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_M_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT UK_M_EMPLOYEE_01 UNIQUE (EMPLOYEE_NO),
    CONSTRAINT FK_M_EMPLOYEE_COMPANY_DIV FOREIGN KEY (COMPANY_DIV) REFERENCES M_COMPANY_DIV (COMPANY_DIV)
);
CREATE INDEX IX_M_EMPLOYEE_01 ON M_EMPLOYEE (COMPANY_DIV, DEPT_CD);

-- 4.3 申込者マスタ
CREATE TABLE M_APPLICANT (
    APPLICANT_ID   BIGINT IDENTITY(1,1) NOT NULL,
    APPLICANT_NO   NVARCHAR(12)   NOT NULL,
    APPLICANT_NAME NVARCHAR(100)  NOT NULL,
    APPLICANT_KANA NVARCHAR(100)  NULL,
    MAIL_ADDRESS   NVARCHAR(254)  NOT NULL,
    TEL_NO         NVARCHAR(15)   NULL,
    ADDRESS        NVARCHAR(200)  NULL,
    CREATED_AT     DATETIME2(3)   NOT NULL,
    CREATED_BY     NVARCHAR(20)   NOT NULL,
    UPDATED_AT     DATETIME2(3)   NOT NULL,
    UPDATED_BY     NVARCHAR(20)   NOT NULL,
    ROW_VERSION    INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_M_APPLICANT PRIMARY KEY (APPLICANT_ID),
    CONSTRAINT UK_M_APPLICANT_01 UNIQUE (APPLICANT_NO)
);

-- 4.4 ステータスマスタ
CREATE TABLE M_STATUS (
    STATUS_CD             CHAR(5)        NOT NULL,
    STATUS_NAME           NVARCHAR(40)   NOT NULL,
    APPLICANT_STATUS_NAME NVARCHAR(30)   NULL,
    CATEGORY_L            CHAR(1)        NOT NULL,
    CATEGORY_M            CHAR(2)        NOT NULL,
    CATEGORY_S            CHAR(2)        NOT NULL,
    ACTOR_TYPE            CHAR(1)        NOT NULL,
    EDITABLE_FLG          CHAR(1)        NOT NULL,
    DISPLAY_ORDER         INT            NOT NULL,
    DESCRIPTION           NVARCHAR(200)  NULL,
    CREATED_AT            DATETIME2(3)   NOT NULL,
    CREATED_BY            NVARCHAR(20)   NOT NULL,
    UPDATED_AT            DATETIME2(3)   NOT NULL,
    UPDATED_BY            NVARCHAR(20)   NOT NULL,
    ROW_VERSION           INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_M_STATUS PRIMARY KEY (STATUS_CD)
);

-- 4.5 ステータス遷移マスタ
CREATE TABLE M_STATUS_TRANSITION (
    TRANSITION_ID  INT            NOT NULL,
    FROM_STATUS_CD CHAR(5)        NOT NULL,
    ACTION_CD      CHAR(2)        NOT NULL,
    CONDITION_CD   CHAR(2)        NOT NULL,
    EVAL_ORDER     INT            NOT NULL,
    TO_STATUS_CD   CHAR(5)        NOT NULL,
    ACTOR_TYPE     CHAR(1)        NOT NULL,
    PRE_CHECK_COND CHAR(1)        NOT NULL,
    REF_NO         NVARCHAR(20)   NULL,
    CREATED_AT     DATETIME2(3)   NOT NULL,
    CREATED_BY     NVARCHAR(20)   NOT NULL,
    UPDATED_AT     DATETIME2(3)   NOT NULL,
    UPDATED_BY     NVARCHAR(20)   NOT NULL,
    ROW_VERSION    INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_M_STATUS_TRANSITION PRIMARY KEY (TRANSITION_ID),
    CONSTRAINT UK_M_STATUS_TRANSITION_01 UNIQUE (FROM_STATUS_CD, ACTION_CD, PRE_CHECK_COND, EVAL_ORDER),
    CONSTRAINT FK_M_STATUS_TRANSITION_FROM FOREIGN KEY (FROM_STATUS_CD) REFERENCES M_STATUS (STATUS_CD),
    CONSTRAINT FK_M_STATUS_TRANSITION_TO FOREIGN KEY (TO_STATUS_CD) REFERENCES M_STATUS (STATUS_CD)
);

-- 4.6 承認ルートマスタ
CREATE TABLE M_APPROVAL_ROUTE (
    ROUTE_ID       BIGINT IDENTITY(1,1) NOT NULL,
    COMPANY_DIV    CHAR(1)        NOT NULL,
    DEPT_CD        NVARCHAR(10)   NOT NULL,
    APPROVAL_TYPE  CHAR(2)        NOT NULL,
    ROUTE_NAME     NVARCHAR(50)   NOT NULL,
    VALID_FROM     DATE           NOT NULL,
    VALID_TO       DATE           NULL,
    CREATED_AT     DATETIME2(3)   NOT NULL,
    CREATED_BY     NVARCHAR(20)   NOT NULL,
    UPDATED_AT     DATETIME2(3)   NOT NULL,
    UPDATED_BY     NVARCHAR(20)   NOT NULL,
    ROW_VERSION    INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_M_APPROVAL_ROUTE PRIMARY KEY (ROUTE_ID),
    CONSTRAINT FK_M_APPROVAL_ROUTE_COMPANY_DIV FOREIGN KEY (COMPANY_DIV) REFERENCES M_COMPANY_DIV (COMPANY_DIV)
);
CREATE INDEX IX_M_APPROVAL_ROUTE_01 ON M_APPROVAL_ROUTE (COMPANY_DIV, DEPT_CD, APPROVAL_TYPE, VALID_FROM);

-- 4.7 承認ルート明細
CREATE TABLE M_APPROVAL_ROUTE_STEP (
    ROUTE_ID             BIGINT         NOT NULL,
    STEP_NO              INT            NOT NULL,
    APPROVER_EMPLOYEE_ID BIGINT         NOT NULL,
    CREATED_AT           DATETIME2(3)   NOT NULL,
    CREATED_BY           NVARCHAR(20)   NOT NULL,
    UPDATED_AT           DATETIME2(3)   NOT NULL,
    UPDATED_BY           NVARCHAR(20)   NOT NULL,
    ROW_VERSION          INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_M_APPROVAL_ROUTE_STEP PRIMARY KEY (ROUTE_ID, STEP_NO),
    CONSTRAINT FK_M_APPROVAL_ROUTE_STEP_ROUTE FOREIGN KEY (ROUTE_ID) REFERENCES M_APPROVAL_ROUTE (ROUTE_ID),
    CONSTRAINT FK_M_APPROVAL_ROUTE_STEP_EMP FOREIGN KEY (APPROVER_EMPLOYEE_ID) REFERENCES M_EMPLOYEE (EMPLOYEE_ID)
);

-- 4.8 一括取込
CREATE TABLE T_IMPORT_BATCH (
    IMPORT_BATCH_ID    BIGINT IDENTITY(1,1) NOT NULL,
    FILE_NAME          NVARCHAR(255)  NOT NULL,
    IMPORT_EMPLOYEE_ID BIGINT         NOT NULL,
    IMPORTED_AT        DATETIME2(3)   NOT NULL,
    TOTAL_COUNT        INT            NOT NULL,
    SUCCESS_COUNT      INT            NOT NULL,
    ERROR_COUNT        INT            NOT NULL,
    CREATED_AT         DATETIME2(3)   NOT NULL,
    CREATED_BY         NVARCHAR(20)   NOT NULL,
    UPDATED_AT         DATETIME2(3)   NOT NULL,
    UPDATED_BY         NVARCHAR(20)   NOT NULL,
    ROW_VERSION        INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_T_IMPORT_BATCH PRIMARY KEY (IMPORT_BATCH_ID),
    CONSTRAINT FK_T_IMPORT_BATCH_EMP FOREIGN KEY (IMPORT_EMPLOYEE_ID) REFERENCES M_EMPLOYEE (EMPLOYEE_ID)
);

-- 4.9 取込エラー
CREATE TABLE T_IMPORT_ERROR (
    IMPORT_BATCH_ID BIGINT         NOT NULL,
    LINE_NO         INT            NOT NULL,
    ERROR_MESSAGE   NVARCHAR(500)  NOT NULL,
    RAW_LINE        NVARCHAR(2000) NULL,
    CREATED_AT      DATETIME2(3)   NOT NULL,
    CREATED_BY      NVARCHAR(20)   NOT NULL,
    UPDATED_AT      DATETIME2(3)   NOT NULL,
    UPDATED_BY      NVARCHAR(20)   NOT NULL,
    ROW_VERSION     INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_T_IMPORT_ERROR PRIMARY KEY (IMPORT_BATCH_ID, LINE_NO),
    CONSTRAINT FK_T_IMPORT_ERROR_BATCH FOREIGN KEY (IMPORT_BATCH_ID) REFERENCES T_IMPORT_BATCH (IMPORT_BATCH_ID)
);

-- 4.10 申込
CREATE TABLE T_APPLICATION (
    APPLICATION_ID        BIGINT IDENTITY(1,1) NOT NULL,
    APPLICATION_NO        NVARCHAR(12)   NOT NULL,
    APPLICANT_ID          BIGINT         NOT NULL,
    OWNER_EMPLOYEE_ID     BIGINT         NOT NULL,
    COMPANY_DIV           CHAR(1)        NOT NULL,
    DEPT_CD               NVARCHAR(10)   NOT NULL,
    STATUS_CD             CHAR(5)        NOT NULL,
    CURRENT_VERSION_NO    INT            NOT NULL,
    BASE_VERSION_NO       INT            NULL,
    REVIEWED_VERSION_NO   INT            NULL,
    REGISTRATION_TYPE     CHAR(1)        NOT NULL,
    SOURCE_APPLICATION_ID BIGINT         NULL,
    IMPORT_BATCH_ID       BIGINT         NULL,
    REVIEWED_AT           DATETIME2(3)   NULL,
    CREATED_AT            DATETIME2(3)   NOT NULL,
    CREATED_BY            NVARCHAR(20)   NOT NULL,
    UPDATED_AT            DATETIME2(3)   NOT NULL,
    UPDATED_BY            NVARCHAR(20)   NOT NULL,
    ROW_VERSION           INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_T_APPLICATION PRIMARY KEY (APPLICATION_ID),
    CONSTRAINT UK_T_APPLICATION_01 UNIQUE (APPLICATION_NO),
    CONSTRAINT FK_T_APPLICATION_APPLICANT FOREIGN KEY (APPLICANT_ID) REFERENCES M_APPLICANT (APPLICANT_ID),
    CONSTRAINT FK_T_APPLICATION_OWNER FOREIGN KEY (OWNER_EMPLOYEE_ID) REFERENCES M_EMPLOYEE (EMPLOYEE_ID),
    CONSTRAINT FK_T_APPLICATION_COMPANY_DIV FOREIGN KEY (COMPANY_DIV) REFERENCES M_COMPANY_DIV (COMPANY_DIV),
    CONSTRAINT FK_T_APPLICATION_STATUS FOREIGN KEY (STATUS_CD) REFERENCES M_STATUS (STATUS_CD),
    CONSTRAINT FK_T_APPLICATION_SOURCE FOREIGN KEY (SOURCE_APPLICATION_ID) REFERENCES T_APPLICATION (APPLICATION_ID),
    CONSTRAINT FK_T_APPLICATION_IMPORT FOREIGN KEY (IMPORT_BATCH_ID) REFERENCES T_IMPORT_BATCH (IMPORT_BATCH_ID)
);
CREATE INDEX IX_T_APPLICATION_01 ON T_APPLICATION (STATUS_CD);
CREATE INDEX IX_T_APPLICATION_02 ON T_APPLICATION (OWNER_EMPLOYEE_ID, STATUS_CD);
CREATE INDEX IX_T_APPLICATION_03 ON T_APPLICATION (APPLICANT_ID);

-- 4.11 申込内容（版）
CREATE TABLE T_APPLICATION_VERSION (
    APPLICATION_ID         BIGINT         NOT NULL,
    VERSION_NO             INT            NOT NULL,
    VERSION_TYPE           CHAR(1)        NOT NULL,
    COPIED_FROM_VERSION_NO INT            NULL,
    PRODUCT_CD             NVARCHAR(10)   NOT NULL,
    BASIC_FEE              DECIMAL(13,0)  NOT NULL,
    OPTION_FEE             DECIMAL(13,0)  NOT NULL,
    HANDLING_FEE           DECIMAL(13,0)  NOT NULL,
    TOTAL_AMOUNT           DECIMAL(13,0)  NOT NULL,
    CONTRACT_START_DATE    DATE           NULL,
    CONTRACT_END_DATE      DATE           NULL,
    AMOUNT_RATIO           DECIMAL(7,4)   NULL,
    REMARKS                NVARCHAR(1000) NULL,
    CONFIRMED_AT           DATETIME2(3)   NULL,
    FIXED_FLG              CHAR(1)        NOT NULL,
    CANCELED_FLG           CHAR(1)        NOT NULL,
    CREATED_AT             DATETIME2(3)   NOT NULL,
    CREATED_BY             NVARCHAR(20)   NOT NULL,
    UPDATED_AT             DATETIME2(3)   NOT NULL,
    UPDATED_BY             NVARCHAR(20)   NOT NULL,
    ROW_VERSION            INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_T_APPLICATION_VERSION PRIMARY KEY (APPLICATION_ID, VERSION_NO),
    CONSTRAINT FK_T_APPLICATION_VERSION_APP FOREIGN KEY (APPLICATION_ID) REFERENCES T_APPLICATION (APPLICATION_ID)
);

-- 4.12 承認申請
CREATE TABLE T_APPROVAL_REQUEST (
    APPROVAL_REQUEST_ID BIGINT IDENTITY(1,1) NOT NULL,
    APPLICATION_ID      BIGINT         NOT NULL,
    VERSION_NO          INT            NOT NULL,
    APPROVAL_TYPE       CHAR(2)        NOT NULL,
    ROUTE_ID            BIGINT         NULL,
    REQUEST_EMPLOYEE_ID BIGINT         NOT NULL,
    REQUESTED_AT        DATETIME2(3)   NOT NULL,
    REQUEST_STATUS      CHAR(1)        NOT NULL,
    CURRENT_STEP_NO     INT            NULL,
    FINAL_STEP_NO       INT            NULL,
    COMPLETED_AT        DATETIME2(3)   NULL,
    CREATED_AT          DATETIME2(3)   NOT NULL,
    CREATED_BY          NVARCHAR(20)   NOT NULL,
    UPDATED_AT          DATETIME2(3)   NOT NULL,
    UPDATED_BY          NVARCHAR(20)   NOT NULL,
    ROW_VERSION         INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_T_APPROVAL_REQUEST PRIMARY KEY (APPROVAL_REQUEST_ID),
    CONSTRAINT FK_T_APPROVAL_REQUEST_VER FOREIGN KEY (APPLICATION_ID, VERSION_NO) REFERENCES T_APPLICATION_VERSION (APPLICATION_ID, VERSION_NO),
    CONSTRAINT FK_T_APPROVAL_REQUEST_ROUTE FOREIGN KEY (ROUTE_ID) REFERENCES M_APPROVAL_ROUTE (ROUTE_ID),
    CONSTRAINT FK_T_APPROVAL_REQUEST_EMP FOREIGN KEY (REQUEST_EMPLOYEE_ID) REFERENCES M_EMPLOYEE (EMPLOYEE_ID)
);
CREATE INDEX IX_T_APPROVAL_REQUEST_01 ON T_APPROVAL_REQUEST (APPLICATION_ID, REQUEST_STATUS);

-- 4.13 承認明細
CREATE TABLE T_APPROVAL_STEP (
    APPROVAL_REQUEST_ID  BIGINT         NOT NULL,
    STEP_NO              INT            NOT NULL,
    APPROVER_EMPLOYEE_ID BIGINT         NOT NULL,
    RESULT_CD            CHAR(1)        NOT NULL,
    COMMENT              NVARCHAR(500)  NULL,
    ACTED_AT             DATETIME2(3)   NULL,
    CREATED_AT           DATETIME2(3)   NOT NULL,
    CREATED_BY           NVARCHAR(20)   NOT NULL,
    UPDATED_AT           DATETIME2(3)   NOT NULL,
    UPDATED_BY           NVARCHAR(20)   NOT NULL,
    ROW_VERSION          INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_T_APPROVAL_STEP PRIMARY KEY (APPROVAL_REQUEST_ID, STEP_NO),
    CONSTRAINT FK_T_APPROVAL_STEP_REQ FOREIGN KEY (APPROVAL_REQUEST_ID) REFERENCES T_APPROVAL_REQUEST (APPROVAL_REQUEST_ID),
    CONSTRAINT FK_T_APPROVAL_STEP_EMP FOREIGN KEY (APPROVER_EMPLOYEE_ID) REFERENCES M_EMPLOYEE (EMPLOYEE_ID)
);
CREATE INDEX IX_T_APPROVAL_STEP_01 ON T_APPROVAL_STEP (APPROVER_EMPLOYEE_ID, RESULT_CD);

-- 4.14 申込者同意
CREATE TABLE T_APPLICANT_CONSENT (
    CONSENT_ID           BIGINT IDENTITY(1,1) NOT NULL,
    APPLICATION_ID       BIGINT         NOT NULL,
    VERSION_NO           INT            NOT NULL,
    CONSENT_TYPE         CHAR(1)        NOT NULL,
    ACCESS_TOKEN_HASH    NVARCHAR(64)   NOT NULL,
    TOKEN_EXPIRES_AT     DATETIME2(3)   NOT NULL,
    CONSENT_STATUS       CHAR(1)        NOT NULL,
    CONTENT_CONFIRMED_AT DATETIME2(3)   NULL,
    CONSENTED_AT         DATETIME2(3)   NULL,
    RETURNED_AT          DATETIME2(3)   NULL,
    RETURN_REASON        NVARCHAR(500)  NULL,
    CLIENT_IP            NVARCHAR(45)   NULL,
    CREATED_AT           DATETIME2(3)   NOT NULL,
    CREATED_BY           NVARCHAR(20)   NOT NULL,
    UPDATED_AT           DATETIME2(3)   NOT NULL,
    UPDATED_BY           NVARCHAR(20)   NOT NULL,
    ROW_VERSION          INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_T_APPLICANT_CONSENT PRIMARY KEY (CONSENT_ID),
    CONSTRAINT UK_T_APPLICANT_CONSENT_01 UNIQUE (ACCESS_TOKEN_HASH),
    CONSTRAINT FK_T_APPLICANT_CONSENT_VER FOREIGN KEY (APPLICATION_ID, VERSION_NO) REFERENCES T_APPLICATION_VERSION (APPLICATION_ID, VERSION_NO)
);
CREATE INDEX IX_T_APPLICANT_CONSENT_01 ON T_APPLICANT_CONSENT (APPLICATION_ID, CONSENT_STATUS);

-- 4.15 外部連携
CREATE TABLE T_EXTERNAL_LINK (
    EXTERNAL_LINK_ID    BIGINT IDENTITY(1,1) NOT NULL,
    APPLICATION_ID      BIGINT         NOT NULL,
    VERSION_NO          INT            NOT NULL,
    LINK_TYPE           CHAR(1)        NOT NULL,
    SEND_STATUS         CHAR(1)        NOT NULL,
    RETRY_COUNT         INT            NOT NULL,
    SENT_AT             DATETIME2(3)   NULL,
    ERROR_MESSAGE       NVARCHAR(1000) NULL,
    EXTERNAL_RECEIPT_NO NVARCHAR(30)   NULL,
    RESULT_CD           CHAR(1)        NULL,
    RESULT_RECEIVED_AT  DATETIME2(3)   NULL,
    RESULT_REASON       NVARCHAR(1000) NULL,
    CREATED_AT          DATETIME2(3)   NOT NULL,
    CREATED_BY          NVARCHAR(20)   NOT NULL,
    UPDATED_AT          DATETIME2(3)   NOT NULL,
    UPDATED_BY          NVARCHAR(20)   NOT NULL,
    ROW_VERSION         INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_T_EXTERNAL_LINK PRIMARY KEY (EXTERNAL_LINK_ID),
    CONSTRAINT FK_T_EXTERNAL_LINK_VER FOREIGN KEY (APPLICATION_ID, VERSION_NO) REFERENCES T_APPLICATION_VERSION (APPLICATION_ID, VERSION_NO)
);
CREATE INDEX IX_T_EXTERNAL_LINK_01 ON T_EXTERNAL_LINK (SEND_STATUS);
CREATE INDEX IX_T_EXTERNAL_LINK_02 ON T_EXTERNAL_LINK (APPLICATION_ID, VERSION_NO);
-- 外部受付番号の UK（NULL 除外のフィルタ付き）は db/vendor/{DBMS} の V1_1 で作成する

-- 4.16 通知
CREATE TABLE T_NOTIFICATION (
    NOTIFICATION_ID   BIGINT IDENTITY(1,1) NOT NULL,
    NOTIFICATION_TYPE CHAR(2)        NOT NULL,
    APPLICATION_ID    BIGINT         NOT NULL,
    TO_ADDRESS        NVARCHAR(254)  NOT NULL,
    SUBJECT           NVARCHAR(200)  NOT NULL,
    BODY              NVARCHAR(4000) NOT NULL,
    SEND_STATUS       CHAR(1)        NOT NULL,
    RETRY_COUNT       INT            NOT NULL,
    SENT_AT           DATETIME2(3)   NULL,
    ERROR_MESSAGE     NVARCHAR(1000) NULL,
    CREATED_AT        DATETIME2(3)   NOT NULL,
    CREATED_BY        NVARCHAR(20)   NOT NULL,
    UPDATED_AT        DATETIME2(3)   NOT NULL,
    UPDATED_BY        NVARCHAR(20)   NOT NULL,
    ROW_VERSION       INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_T_NOTIFICATION PRIMARY KEY (NOTIFICATION_ID),
    CONSTRAINT FK_T_NOTIFICATION_APP FOREIGN KEY (APPLICATION_ID) REFERENCES T_APPLICATION (APPLICATION_ID)
);
CREATE INDEX IX_T_NOTIFICATION_01 ON T_NOTIFICATION (SEND_STATUS, CREATED_AT);

-- 4.17 ステータス履歴
CREATE TABLE T_STATUS_HISTORY (
    STATUS_HISTORY_ID BIGINT IDENTITY(1,1) NOT NULL,
    APPLICATION_ID    BIGINT         NOT NULL,
    VERSION_NO        INT            NOT NULL,
    FROM_STATUS_CD    CHAR(5)        NULL,
    TO_STATUS_CD      CHAR(5)        NOT NULL,
    TRANSITION_ID     INT            NULL,
    ACTION_CD         CHAR(2)        NOT NULL,
    ACTOR_TYPE        CHAR(1)        NOT NULL,
    ACTOR_ID          NVARCHAR(20)   NOT NULL,
    COMMENT           NVARCHAR(500)  NULL,
    CHANGED_AT        DATETIME2(3)   NOT NULL,
    CREATED_AT        DATETIME2(3)   NOT NULL,
    CREATED_BY        NVARCHAR(20)   NOT NULL,
    UPDATED_AT        DATETIME2(3)   NOT NULL,
    UPDATED_BY        NVARCHAR(20)   NOT NULL,
    ROW_VERSION       INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_T_STATUS_HISTORY PRIMARY KEY (STATUS_HISTORY_ID),
    CONSTRAINT FK_T_STATUS_HISTORY_APP FOREIGN KEY (APPLICATION_ID) REFERENCES T_APPLICATION (APPLICATION_ID),
    CONSTRAINT FK_T_STATUS_HISTORY_TRANS FOREIGN KEY (TRANSITION_ID) REFERENCES M_STATUS_TRANSITION (TRANSITION_ID)
);
CREATE INDEX IX_T_STATUS_HISTORY_01 ON T_STATUS_HISTORY (APPLICATION_ID, CHANGED_AT);

-- 申込番号の採番（14. 共通仕様 4 章）
CREATE SEQUENCE SEQ_APPLICATION_NO AS BIGINT START WITH 1 INCREMENT BY 1;
