-- V5_2 既存データの移行：申込者マスタの申込者情報を、その申込のすべての版へ写す
UPDATE T_APPLICATION_VERSION SET
    APPLICANT_NAME = (SELECT p.APPLICANT_NAME FROM T_APPLICATION a JOIN M_APPLICANT p ON p.APPLICANT_ID = a.APPLICANT_ID WHERE a.APPLICATION_ID = T_APPLICATION_VERSION.APPLICATION_ID),
    APPLICANT_KANA = (SELECT p.APPLICANT_KANA FROM T_APPLICATION a JOIN M_APPLICANT p ON p.APPLICANT_ID = a.APPLICANT_ID WHERE a.APPLICATION_ID = T_APPLICATION_VERSION.APPLICATION_ID),
    TEL_NO         = (SELECT p.TEL_NO         FROM T_APPLICATION a JOIN M_APPLICANT p ON p.APPLICANT_ID = a.APPLICANT_ID WHERE a.APPLICATION_ID = T_APPLICATION_VERSION.APPLICATION_ID),
    MAIL_ADDRESS   = (SELECT p.MAIL_ADDRESS   FROM T_APPLICATION a JOIN M_APPLICANT p ON p.APPLICANT_ID = a.APPLICANT_ID WHERE a.APPLICATION_ID = T_APPLICATION_VERSION.APPLICATION_ID),
    ADDRESS        = (SELECT p.ADDRESS        FROM T_APPLICATION a JOIN M_APPLICANT p ON p.APPLICANT_ID = a.APPLICANT_ID WHERE a.APPLICATION_ID = T_APPLICATION_VERSION.APPLICATION_ID);

-- アカウント未発行（パスワードなし）の行はログイン用のデータではないため、申込との紐づけを外して削除する。
-- その申込は一次承認が通ったときに申込者アカウントを発行して紐づける
UPDATE T_APPLICATION SET APPLICANT_ID = NULL WHERE APPLICANT_ID IN (SELECT APPLICANT_ID FROM M_APPLICANT WHERE PASSWORD_HASH IS NULL);
DELETE FROM M_APPLICANT WHERE PASSWORD_HASH IS NULL;

-- 申込者マスタからは申込者情報の列を削除し、ログインに必要なデータだけを残す
ALTER TABLE M_APPLICANT DROP COLUMN APPLICANT_NAME;
ALTER TABLE M_APPLICANT DROP COLUMN APPLICANT_KANA;
ALTER TABLE M_APPLICANT DROP COLUMN MAIL_ADDRESS;
ALTER TABLE M_APPLICANT DROP COLUMN TEL_NO;
ALTER TABLE M_APPLICANT DROP COLUMN ADDRESS;
