-- V5 申込者情報（申込者名・申込者名カナ・電話番号・メールアドレス・住所）を申込データ（申込内容の版）に持たせる。
-- ログインに必要なデータ（ユーザー ID・パスワード）は申込者アカウント（V5_3 で M_APPLICANT を改名）に分ける。
-- 処理順：V5 列追加 → V5_1（DB 別）申込の申込者 ID を NULL 可に → V5_2 既存データの移行 → V5_3（DB 別）改名と外部キー
ALTER TABLE T_APPLICATION_VERSION ADD APPLICANT_NAME NVARCHAR(100) NULL;
ALTER TABLE T_APPLICATION_VERSION ADD APPLICANT_KANA NVARCHAR(100) NULL;
ALTER TABLE T_APPLICATION_VERSION ADD TEL_NO NVARCHAR(15) NULL;
ALTER TABLE T_APPLICATION_VERSION ADD MAIL_ADDRESS NVARCHAR(254) NULL;
ALTER TABLE T_APPLICATION_VERSION ADD ADDRESS NVARCHAR(200) NULL;
