-- V6_1 既存の版に申込の担当（会社区分・部署・担当社員）を複写し、部署マスタへの外部キーを張る
UPDATE T_APPLICATION_VERSION SET
    COMPANY_DIV = (SELECT a.COMPANY_DIV FROM T_APPLICATION a WHERE a.APPLICATION_ID = T_APPLICATION_VERSION.APPLICATION_ID),
    DEPT_CD = (SELECT a.DEPT_CD FROM T_APPLICATION a WHERE a.APPLICATION_ID = T_APPLICATION_VERSION.APPLICATION_ID),
    OWNER_EMPLOYEE_ID = (SELECT a.OWNER_EMPLOYEE_ID FROM T_APPLICATION a WHERE a.APPLICATION_ID = T_APPLICATION_VERSION.APPLICATION_ID);

ALTER TABLE M_EMPLOYEE ADD CONSTRAINT FK_M_EMPLOYEE_DEPARTMENT FOREIGN KEY (COMPANY_DIV, DEPT_CD) REFERENCES M_DEPARTMENT (COMPANY_DIV, DEPT_CD);
ALTER TABLE M_APPROVAL_ROUTE ADD CONSTRAINT FK_M_APPROVAL_ROUTE_DEPARTMENT FOREIGN KEY (COMPANY_DIV, DEPT_CD) REFERENCES M_DEPARTMENT (COMPANY_DIV, DEPT_CD);
ALTER TABLE T_APPLICATION ADD CONSTRAINT FK_T_APPLICATION_DEPARTMENT FOREIGN KEY (COMPANY_DIV, DEPT_CD) REFERENCES M_DEPARTMENT (COMPANY_DIV, DEPT_CD);
