-- V6 部署マスタ（会社 > 部署 > 担当者の階層の「部署」）と、申込の版に担当（会社区分・部署・担当社員）を記録する列を追加する。
-- 処理順：V6 部署マスタの作成と初期化・版の列追加 → V6_1 既存の版への複写と外部キー

-- 部署マスタ：会社区分ごとの部署コードと部署名。部署コードは会社区分の中で一意
CREATE TABLE M_DEPARTMENT (
    COMPANY_DIV    CHAR(1)        NOT NULL,
    DEPT_CD        NVARCHAR(10)   NOT NULL,
    DEPT_NAME      NVARCHAR(50)   NOT NULL,
    VALID_FLG      CHAR(1)        NOT NULL,
    CREATED_AT     DATETIME2(3)   NOT NULL,
    CREATED_BY     NVARCHAR(20)   NOT NULL,
    UPDATED_AT     DATETIME2(3)   NOT NULL,
    UPDATED_BY     NVARCHAR(20)   NOT NULL,
    ROW_VERSION    INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_M_DEPARTMENT PRIMARY KEY (COMPANY_DIV, DEPT_CD),
    CONSTRAINT FK_M_DEPARTMENT_COMPANY_DIV FOREIGN KEY (COMPANY_DIV) REFERENCES M_COMPANY_DIV (COMPANY_DIV)
);

-- 既存の社員・承認ルート・申込で使われている部署コードから作る。初期データの部署（100・200・900）は承認ルート名に合わせた名称、
-- それ以外は「部署 + コード」の仮の名称とし、管理者が部署マスタ画面（SC16）で直す
INSERT INTO M_DEPARTMENT (COMPANY_DIV, DEPT_CD, DEPT_NAME, VALID_FLG, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, ROW_VERSION)
SELECT d.COMPANY_DIV, d.DEPT_CD,
       CASE WHEN d.COMPANY_DIV = '1' AND d.DEPT_CD = '100' THEN N'営業部'
            WHEN d.COMPANY_DIV = '1' AND d.DEPT_CD = '900' THEN N'管理部'
            WHEN d.COMPANY_DIV = '2' AND d.DEPT_CD = '200' THEN N'営業部'
            ELSE CONCAT(N'部署 ', d.DEPT_CD) END,
       '1', '2026-10-04 00:00:00', 'SYSTEM', '2026-10-04 00:00:00', 'SYSTEM', 1
FROM (SELECT COMPANY_DIV, DEPT_CD FROM M_EMPLOYEE
      UNION SELECT COMPANY_DIV, DEPT_CD FROM M_APPROVAL_ROUTE
      UNION SELECT COMPANY_DIV, DEPT_CD FROM T_APPLICATION) d;

-- 申込の版に担当を記録する（全体修正で変えた場合の差分表示・履歴のため）。申込（T_APPLICATION）の値が現在の担当で、現行版と同じ値を持つ
ALTER TABLE T_APPLICATION_VERSION ADD COMPANY_DIV CHAR(1) NULL;
ALTER TABLE T_APPLICATION_VERSION ADD DEPT_CD NVARCHAR(10) NULL;
ALTER TABLE T_APPLICATION_VERSION ADD OWNER_EMPLOYEE_ID BIGINT NULL;
