-- V7 会社B（会社区分 2）だけの申込の入力項目を申込内容（版）に追加する。
-- 項目名・桁はサンプル（実際の項目が決まったら差し替える）。入力するだけで、項目を使った制御（遷移・判定・連携）はない。
-- 会社区分 2 以外の申込では常に空。
ALTER TABLE T_APPLICATION_VERSION ADD CORPORATE_NO NVARCHAR(13) NULL;
ALTER TABLE T_APPLICATION_VERSION ADD INSTALL_PLACE NVARCHAR(200) NULL;
ALTER TABLE T_APPLICATION_VERSION ADD CONTACT_MEMO NVARCHAR(500) NULL;
