-- V8 同意事項 PDF（版管理）と、同意ごとの閲覧・同意の記録、申込内容 PDF（同意時・審査完了時）を保存するテーブル。
-- サンプルの同意事項（PDF）は V8_1（Java マイグレーション）で登録する。

-- 同意事項マスタ：申込同意確認画面（AP03）に表示する同意事項の文書。対象 1：新規申込、2：契約変更、9：共通
CREATE TABLE M_CONSENT_DOCUMENT (
    DOCUMENT_CD    NVARCHAR(20)   NOT NULL,
    DOCUMENT_NAME  NVARCHAR(100)  NOT NULL,
    TARGET_TYPE    CHAR(1)        NOT NULL,
    DISPLAY_ORDER  INT            NOT NULL,
    VALID_FLG      CHAR(1)        NOT NULL,
    CREATED_AT     DATETIME2(3)   NOT NULL,
    CREATED_BY     NVARCHAR(20)   NOT NULL,
    UPDATED_AT     DATETIME2(3)   NOT NULL,
    UPDATED_BY     NVARCHAR(20)   NOT NULL,
    ROW_VERSION    INT            NOT NULL DEFAULT 1,
    CONSTRAINT PK_M_CONSENT_DOCUMENT PRIMARY KEY (DOCUMENT_CD)
);

-- 同意事項の版：PDF 本体とハッシュ。版は追加するだけで上書き・削除しない。適用開始日時が現在以前で最も新しい版を表示する
CREATE TABLE M_CONSENT_DOCUMENT_VERSION (
    DOCUMENT_CD    NVARCHAR(20)    NOT NULL,
    VERSION_NO     INT             NOT NULL,
    EFFECTIVE_FROM DATETIME2(3)    NOT NULL,
    FILE_NAME      NVARCHAR(200)   NOT NULL,
    FILE_SIZE      INT             NOT NULL,
    FILE_HASH      CHAR(64)        NOT NULL,
    FILE_DATA      VARBINARY(MAX)  NOT NULL,
    REMARKS        NVARCHAR(200)   NULL,
    CREATED_AT     DATETIME2(3)    NOT NULL,
    CREATED_BY     NVARCHAR(20)    NOT NULL,
    UPDATED_AT     DATETIME2(3)    NOT NULL,
    UPDATED_BY     NVARCHAR(20)    NOT NULL,
    ROW_VERSION    INT             NOT NULL DEFAULT 1,
    CONSTRAINT PK_M_CONSENT_DOCUMENT_VERSION PRIMARY KEY (DOCUMENT_CD, VERSION_NO),
    CONSTRAINT FK_M_CONSENT_DOCUMENT_VERSION_DOC FOREIGN KEY (DOCUMENT_CD) REFERENCES M_CONSENT_DOCUMENT (DOCUMENT_CD)
);

-- 申込者同意の同意事項：同意（確認依頼）ごとに、どの同意事項のどの版を開いたか（閲覧日時）と同意したか（同意日時）
CREATE TABLE T_APPLICANT_CONSENT_DOCUMENT (
    CONSENT_ID     BIGINT          NOT NULL,
    DOCUMENT_CD    NVARCHAR(20)    NOT NULL,
    VERSION_NO     INT             NOT NULL,
    VIEWED_AT      DATETIME2(3)    NOT NULL,
    AGREED_AT      DATETIME2(3)    NULL,
    CREATED_AT     DATETIME2(3)    NOT NULL,
    CREATED_BY     NVARCHAR(20)    NOT NULL,
    UPDATED_AT     DATETIME2(3)    NOT NULL,
    UPDATED_BY     NVARCHAR(20)    NOT NULL,
    ROW_VERSION    INT             NOT NULL DEFAULT 1,
    CONSTRAINT PK_T_APPLICANT_CONSENT_DOCUMENT PRIMARY KEY (CONSENT_ID, DOCUMENT_CD, VERSION_NO),
    CONSTRAINT FK_T_APPLICANT_CONSENT_DOCUMENT_CONSENT FOREIGN KEY (CONSENT_ID) REFERENCES T_APPLICANT_CONSENT (CONSENT_ID),
    CONSTRAINT FK_T_APPLICANT_CONSENT_DOCUMENT_VERSION FOREIGN KEY (DOCUMENT_CD, VERSION_NO) REFERENCES M_CONSENT_DOCUMENT_VERSION (DOCUMENT_CD, VERSION_NO)
);

-- 申込内容 PDF：種別 1：同意時（申込者同意ごと）、2：審査完了時。作成後は変更しない
CREATE TABLE T_APPLICATION_PDF (
    PDF_ID         BIGINT IDENTITY(1,1) NOT NULL,
    APPLICATION_ID BIGINT          NOT NULL,
    VERSION_NO     INT             NOT NULL,
    PDF_TYPE       CHAR(1)         NOT NULL,
    CONSENT_ID     BIGINT          NULL,
    FILE_NAME      NVARCHAR(200)   NOT NULL,
    FILE_SIZE      INT             NOT NULL,
    FILE_HASH      CHAR(64)        NOT NULL,
    FILE_DATA      VARBINARY(MAX)  NOT NULL,
    CREATED_AT     DATETIME2(3)    NOT NULL,
    CREATED_BY     NVARCHAR(20)    NOT NULL,
    UPDATED_AT     DATETIME2(3)    NOT NULL,
    UPDATED_BY     NVARCHAR(20)    NOT NULL,
    ROW_VERSION    INT             NOT NULL DEFAULT 1,
    CONSTRAINT PK_T_APPLICATION_PDF PRIMARY KEY (PDF_ID),
    CONSTRAINT FK_T_APPLICATION_PDF_VERSION FOREIGN KEY (APPLICATION_ID, VERSION_NO) REFERENCES T_APPLICATION_VERSION (APPLICATION_ID, VERSION_NO),
    CONSTRAINT FK_T_APPLICATION_PDF_CONSENT FOREIGN KEY (CONSENT_ID) REFERENCES T_APPLICANT_CONSENT (CONSENT_ID)
);
CREATE INDEX IX_T_APPLICATION_PDF_01 ON T_APPLICATION_PDF (APPLICATION_ID);
